# Change these first
owner: junglewp # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Mainnet
    url: https://www.junglewp.com
  - name: Testnet
    url: https://testnet.devops.junglewp.io
  - name: Support
    url: https://docs.junglewp.com
  - name: Community
    url: https://teams.junglewp.io
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.junglewp.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/junglewp/status/master/assets/elephant_logo.svg
  name: JungleWP
  introTitle: "**JungleWP** Keep up to date with real-time and historical interruptions to our service which may be affecting you."
  introMessage: Real-time problems and outages for JungleWP Web Platform on both Mainnet and Testnet.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
